import './globals.css';
import type {Metadata} from 'next';

import NavigationBar from '@/components/NavigationBar';

export const metadata: Metadata = {
  title: 'Inicio',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="es">
      <body>
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}
