import type {Metadata} from 'next';
import Image from 'next/image';

import prueba from '@/../public/prueba.jpg';
export const metadata: Metadata = {
  title: 'Login',
  description: 'Generated by create next app',
};

export default function LoginLayout({children}: {children: React.ReactNode}) {
  return (
    <main className="relative flex h-[100vh] flex-wrap items-center justify-center">
      <Image
        alt="background"
        className="absolute -z-10 aspect-square h-[100vh] min-w-full bg-black/25 object-cover object-center blur transition-colors ease-in-out hover:bg-black/10"
        height={200}
        quality={100}
        src={prueba}
      />
      {children}
    </main>
  );
}
